name: "Build and Deploy"
on:
  push:
    branches:
    - master
    paths:
    - src/*
    - src/*/*
    - src/*/*/*
    - src/*/*/*/*
    - src/*/*/*/*/*
    - .github/workflows/main.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://squidfunk/mkdocs-material@sha256:5282540ecb411db49a2ae3ccea3b00a0ab1f55ecd8151e2941cf0ccad69d2beb
        with:
          args: "build"
      - uses: docker://cardboardci/netlify:latest
        with:
          args: "netlify deploy --dir public --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_TOKEN }} --prod"